/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.PharmacyEnterpriseRole;

import Business.Customer.CustomerDirectory;
import Business.Ecosystem;
import javax.swing.JPanel;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pannaga
 */
public class ManagePharmaOrdersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePharmaOrdersJPanel
     */
    
    private JPanel userProcessContainer;
    private Ecosystem business;
    private CustomerDirectory customerDirectory;
     
    public ManagePharmaOrdersJPanel(JPanel userProcessContainer, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        
        for(Network n : business.getNetworks()){
            this.customerDirectory = n.getCustomerDirectory();
        }
        
        displaycombobox();
        populateCustomerOrderTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerJTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        comboDeliveryAgent = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Product ID", "Name", "Location", "Zipcode", "Price", "Delivery agent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 803, 186));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 54, -1, -1));

        comboDeliveryAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeliveryAgentActionPerformed(evt);
            }
        });
        add(comboDeliveryAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 148, -1));

        jLabel1.setText("Assign Delivery agent");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jButton1.setText("Assign");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 105, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboDeliveryAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeliveryAgentActionPerformed
        // TODO add your handling code here:

        
        
    }//GEN-LAST:event_comboDeliveryAgentActionPerformed

    private void populateCustomerOrderTable() {
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> comboDeliveryAgent;
    private javax.swing.JTable customerJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void displaycombobox() {
        
        
    }
}
