/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LabSamples;

import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Products.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PrescriptionUploadWorkRequest;
import Business.WorkQueue.ReportUploadWorkRequest;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vachanabelgavi
 */
public class LabReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabReportJPanel
     */
    private final JPanel userprocesscontainer;
    private final Ecosystem ecosystem;
    private final Network network;
    private final UserAccount user;
    private final Enterprise enterprise;

    ArrayList<ReportUploadWorkRequest> workrequest;
    private final Organization organization;
    private ReportUploadWorkRequest currentWorkingRequest;

    DefaultTableModel tableModel;
    
    public LabReportJPanel(JPanel userProcessContainer, Ecosystem system, UserAccount user, Network network, Organization organization, Enterprise enterprise) {
        initComponents();
        
        this.userprocesscontainer = userProcessContainer;
        this.ecosystem = system;
        this.network = network;
        this.enterprise = enterprise;
        this.user = user;
        this.organization = organization;

        this.workrequest = this.ecosystem.getReportWorkList();
        this.tableModel = (DefaultTableModel) jTable2.getModel();
        if (workrequest.size() != 0) {
//            populate prescription dropdown
//populate product dropdown
            populateReports();
            populateProducts();

        } else {
            JOptionPane.showMessageDialog(null, "No Prescription Requests!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        dropdownPrescription = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelCustomerName = new javax.swing.JLabel();
        labelNetwork = new javax.swing.JLabel();
        labelDoctorSign = new javax.swing.JLabel();
        labelOrderId = new javax.swing.JLabel();
        labelOrderStatus = new javax.swing.JLabel();
        createOrderbttn = new javax.swing.JButton();
        btnGo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PHARMACIST'S PRESCRIPTION WORK AREA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 26, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "PRODUCT NAME", "PRODUCT PRICE", "QTY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 347, -1, 304));

        dropdownPrescription.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(dropdownPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 106, 180, -1));

        jLabel2.setText("CUSTOMER NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 175, -1, -1));

        jLabel3.setText("NETWORK");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 207, -1, -1));

        jLabel4.setText("DOCTOR SIGNATURE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 239, -1, -1));

        jLabel5.setText("ORDER ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 271, -1, -1));

        jLabel6.setText("ORDER STATUS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 304, -1, -1));

        labelCustomerName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 175, 229, 14));

        labelNetwork.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 207, 229, 14));

        labelDoctorSign.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelDoctorSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 239, 229, 14));

        labelOrderId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 271, 229, 14));

        labelOrderStatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelOrderStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 304, 229, 14));

        createOrderbttn.setText("CREATE ORDER");
        jPanel1.add(createOrderbttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 645, -1, -1));

        btnGo.setText("GO");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 105, -1, -1));

        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 79, 368, 507));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 994, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:

        for (ReportUploadWorkRequest wq : this.workrequest) {
            if (wq.getRequestId() == (int) dropdownPrescription.getSelectedItem()) {
                labelCustomerName.setText(wq.getCustomer().getName());
                labelDoctorSign.setText(wq.getSignature());
                labelNetwork.setText(wq.getCustomer().getLocation());
                this.currentWorkingRequest = wq;

                if (wq.getReport()!= null) {
                    ImageIcon ii = new ImageIcon(wq.getReport().getAbsolutePath());
                    jLabel7.setIcon(ii);
                }
                break;
            }
        }
    }//GEN-LAST:event_btnGoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JButton createOrderbttn;
    private javax.swing.JComboBox dropdownPrescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelCustomerName;
    private javax.swing.JLabel labelDoctorSign;
    private javax.swing.JLabel labelNetwork;
    private javax.swing.JLabel labelOrderId;
    private javax.swing.JLabel labelOrderStatus;
    // End of variables declaration//GEN-END:variables

    public void populateReports() {

        for (ReportUploadWorkRequest pu : this.workrequest) {
            if (pu.getReceiver().getUsername().equals(user.getUsername())) {
                dropdownPrescription.addItem(pu.getRequestId());
            }

        }

    }

    public void populateProducts() {
        try {
            tableModel.setRowCount(0);

            for (Product p : organization.getOrganizationProducts()) {
                tableModel.insertRow(tableModel.getRowCount(), new Object[]{
                    p.getProductId(),
                    p.getName(),
                    p.getPrice(),
                    p.getStockunits(),
                    1
                });
            }

        } catch (Exception e) {

        }

    }
}
