/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdmin;

import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Role.EquipmentEnterpriseRole;
import Business.Enterprise.Role.LabEnterprise;
import Business.Enterprise.Role.PharmaceuticalEnterpriseAdminRole;
import Business.Enterprise.Role.VaccinationEnterpriseRole;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.ValidationClass;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Nidhi Raghavendra
 */
public class ManageOrganizationAdminsJPanel extends javax.swing.JPanel {

    private final JPanel userProcessContainer;
    private final Ecosystem ecosystem;
    Network network;
    Enterprise enterprise;
    Organization organization;
    Role role;
    UserAccount account;

    /**
     * Creates new form ManageOrganizationAdminsJPanel
     */
    public ManageOrganizationAdminsJPanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.ecosystem = system;
        populateNetworks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        comboNetwork = new javax.swing.JComboBox();
        comboEnteprise = new javax.swing.JComboBox();
        comboOrg = new javax.swing.JComboBox();
        txtName = new javax.swing.JTextField();
        comboRole = new javax.swing.JComboBox();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(253, 252, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network name", "Enterprise name", "Organization name", "username", "password", "employee"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 756, 260));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/icons8-back-50.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 70));

        comboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetworkActionPerformed(evt);
            }
        });
        add(comboNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 150, -1));

        comboEnteprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEntepriseActionPerformed(evt);
            }
        });
        add(comboEnteprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 150, -1));

        add(comboOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 150, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 150, -1));

        add(comboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 150, -1));
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 150, -1));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, 150, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Images/icons8-organization-50.png"))); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 750, 160, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 50, -1));

        jLabel4.setText("Username");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, -1, -1));

        jLabel7.setText("Password");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 60, -1));

        jLabel1.setBackground(new java.awt.Color(253, 252, 249));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Organizations");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void comboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetworkActionPerformed
        // TODO add your handling code here:
        populateEnteprise((Network) comboNetwork.getSelectedItem());
    }//GEN-LAST:event_comboNetworkActionPerformed

    private void comboEntepriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEntepriseActionPerformed
        // TODO add your handling code here:
        populateOrgs((Enterprise) comboEnteprise.getSelectedItem());
    }//GEN-LAST:event_comboEntepriseActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Network network = (Network) comboNetwork.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) comboEnteprise.getSelectedItem();

        Organization.Type orgtype = (Organization.Type) comboOrg.getSelectedItem();
        Role.RoleType roletype = (Role.RoleType) comboRole.getSelectedItem();

        if (network == null || type == null || orgtype == null || roletype == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        if (txtName.getText().isEmpty() || txtUsername.getText().isEmpty() || txtPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields cannot be empty!");
        }

        String name = txtName.getText();
        String username = txtUsername.getText();
        String password = txtPassword.getText();

        ValidationClass v = new ValidationClass();
        v.validateName(name);
        v.validateUsername(username);
        v.validatePassword(String.valueOf(password));

        boolean flag = ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(username);
        if (flag == false) {
            JOptionPane.showMessageDialog(null, "User name already exists");
        }else{
            Employee employee = new Employee();
            
            ecosystem.getUserAccountDirectory().createUserAccount(username, password, employee, role);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateNetworks() {
        try {
            for (Network n : this.ecosystem.getNetworks()) {
                if (n != null) {
                    comboNetwork.addItem(n);
                }
            }

        } catch (Exception e) {

        }
    }

    public void populateEnteprise(Network n) {
        try {
            comboEnteprise.removeAllItems();
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                comboEnteprise.addItem(e);
            }
        } catch (Exception e) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboEnteprise;
    private javax.swing.JComboBox comboNetwork;
    private javax.swing.JComboBox comboOrg;
    private javax.swing.JComboBox comboRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void populateOrgs(Enterprise e) {
        try {
            comboOrg.removeAllItems();
            for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                comboOrg.addItem(o);
            }
        } catch (Exception ex) {

        }

    }
}
