/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.SystemAdmin;

import Business.Customer.Customer;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Orders.Order;
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.demo.BarChartDemo1;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Nidhi Raghavendra
 */
public class StatisticsJPanel extends javax.swing.JPanel {

    private final Ecosystem ecosystem;

    /**
     * Creates new form StatisticsJPanel
     */
    public StatisticsJPanel(Ecosystem system) {
        initComponents();

        this.ecosystem = system;

        createBarChart();
        createorderBar();
        createPieChart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderPanel = new javax.swing.JPanel();
        networkPanel = new javax.swing.JPanel();
        deliveryAgentsPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(253, 252, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderPanel.setOpaque(false);

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        add(orderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 910, 580));

        networkPanel.setOpaque(false);

        javax.swing.GroupLayout networkPanelLayout = new javax.swing.GroupLayout(networkPanel);
        networkPanel.setLayout(networkPanelLayout);
        networkPanelLayout.setHorizontalGroup(
            networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        networkPanelLayout.setVerticalGroup(
            networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        add(networkPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 420, 270));

        deliveryAgentsPanel.setOpaque(false);

        javax.swing.GroupLayout deliveryAgentsPanelLayout = new javax.swing.GroupLayout(deliveryAgentsPanel);
        deliveryAgentsPanel.setLayout(deliveryAgentsPanelLayout);
        deliveryAgentsPanelLayout.setHorizontalGroup(
            deliveryAgentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        deliveryAgentsPanelLayout.setVerticalGroup(
            deliveryAgentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        add(deliveryAgentsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 350, 430, 290));
    }// </editor-fold>//GEN-END:initComponents

    public void createBarChart() {
        networkPanel.removeAll();
        JFreeChart barchart = ChartFactory.createBarChart("CUSTOMER NETWORKS", "Network", "Customers", createdataset(), PlotOrientation.HORIZONTAL, true, true, true);
        System.out.println("PLOT ");
        CategoryPlot bar = barchart.getCategoryPlot();

        ChartPanel chartPanel = new ChartPanel(barchart);
        chartPanel.setSize(300, 300);
        chartPanel.setVisible(true);
        chartPanel.setBorder(null);

        System.out.println("CAME HERE ");
        networkPanel.removeAll();
        networkPanel.setSize(300, 300);
        networkPanel.add(chartPanel, BorderLayout.CENTER);

        networkPanel.validate();
    }

    public void createorderBar() {
        orderPanel.removeAll();
        JFreeChart barchart = ChartFactory.createBarChart("ENTERPRISE ORDERS", "Network", "Customers", createorderdata(), PlotOrientation.VERTICAL, true, true, true);
        System.out.println("PLOT ");
        CategoryPlot bar = barchart.getCategoryPlot();

        ChartPanel chartPanel = new ChartPanel(barchart);
        chartPanel.setSize(800, 600);
        chartPanel.setVisible(true);
        chartPanel.setBorder(null);

        System.out.println("CAME HERE ");
        orderPanel.removeAll();
        orderPanel.setSize(800, 800);
        orderPanel.add(chartPanel, BorderLayout.CENTER);

        orderPanel.validate();
    }

    public CategoryDataset createdataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (Network n : this.ecosystem.getNetworks()) {
            dataset.setValue(n.getCustomerDirectory().getCustomerList().size(), n.getNetworkName(), "");
        }

        return dataset;
    }

    public CategoryDataset createorderdata() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        int pordercount = 0;
        int mordercount = 0;
        int lordercount = 0;
        int vordercount = 0;

        for (Network n : this.ecosystem.getNetworks()) {
            for (Customer c : n.getCustomerDirectory().getCustomerList()) {
                for (Order o : c.getOrderlist()) {
                    if (o.getEnterprisename().equals("Medical Equipments")) {
                        mordercount++;
                    }
                    if (o.getEnterprisename().equals("Pharmaceutical")) {
                        pordercount++;
                    }
                    if (o.getEnterprisename().equals("Lab Center & Diagnostics")) {
                        lordercount++;
                    }
                    if (o.getEnterprisename().equals("Immunization & Vaccination")) {
                        vordercount++;
                    }
                }
            }
        }

        dataset.setValue(pordercount, "#orders", "Pharmaceutical");
        dataset.setValue(mordercount, "#orders", "Medical Equipments");
        dataset.setValue(vordercount, "#orders", "Immunization & Vaccination");
        dataset.setValue(lordercount, "#orders", "Lab Center & Diagnostics");

        return dataset;
    }

    public void createPieChart() {
        deliveryAgentsPanel.removeAll();
        JFreeChart pieChart = ChartFactory.createPieChart("Delivery Agents", deliverydataset(), true, true, true);

        pieChart.setBorderVisible(false);

        ChartPanel piechartpanel = new ChartPanel(pieChart);
        piechartpanel.setVisible(true);
        piechartpanel.setSize(300, 300);
        deliveryAgentsPanel.removeAll();
        deliveryAgentsPanel.setSize(300, 300);
        deliveryAgentsPanel.add(piechartpanel, BorderLayout.CENTER);
        deliveryAgentsPanel.validate();

    }

    public DefaultPieDataset deliverydataset() {
        DefaultPieDataset pieset = new DefaultPieDataset();
        int i = 0;
        for (Network n : this.ecosystem.getNetworks()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                i += e.getDeliveryAgentsInEnterpiselist().size();
            }
            pieset.setValue(n.getNetworkName(), i);
            i = 0;
        }

        return pieset;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel deliveryAgentsPanel;
    private javax.swing.JPanel networkPanel;
    private javax.swing.JPanel orderPanel;
    // End of variables declaration//GEN-END:variables
}
